ProjectIntegrador/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^app_dashboard/', include(('app_dashboard.urls', 'app_dashboard'), namespace='app_dashboard')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_dashboard/api/urls.py
from rest_framework import routers

from app_dashboard.api.views import *

router = routers.DefaultRouter()
router.register(r'crear-staff', CrearStaffViewSet, base_name='crear-staff')
router.register(r'crear-producto', CrearProductoViewSet, base_name='crear-producto')
router.register(r'crear-alamacen-producto', CrearAlmacenProductoViewSet, base_name='crear-almacen-producto')
router.register(r'crear-movimiento-producto', CrearMovimientoProductoViewSet, base_name='crear-movimiento-producto')
router.register(r'crear-qr', CrearQRViewSet, base_name='crear-qr')
router.register(r'editar-staff', EditarStaffViewSet, base_name='editar-staff')
router.register(r'editar-producto', EditarProductoViewSet, base_name='editar-producto')
router.register(r'listar-staff', ListarStaffViewSet, base_name='listar-staff')
router.register(r'listar-producto', ListarProductoViewSet, base_name='listar-producto')
router.register(r'listar-almacen-producto', ListarAlmacenProductoViewSet, base_name='listar-almacen-producto')
router.register(r'listar-movimiento-producto', ListarMovimientoProductoViewSet, base_name='listar-movimiento-producto')
router.register(r'eliminar-almacen-producto', EliminarAlmacenProductoViewSet, base_name='eliminar-almacen-producto')
router.register(r'eliminar-movimiento-producto', EliminarMovimientoProductoViewSet, base_name='eliminar-movimiento-producto')
router.register(r'eliminar-producto', EliminarProductoViewSet, base_name='eliminar-producto')
router.register(r'eliminar-staff', EliminarStaffViewSet, base_name='eliminar-staff')

urlpatterns = router.urls

app_dashboard/urls.py
from django.conf.urls import url
from django.urls import include

from app_dashboard.views import *

urlpatterns = [
    url(r'^api/', include(('app_dashboard.api.urls', 'api'), namespace='api')),
    url(r'^login/', LoginViewSet.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='salida'),
    url(r'^registro-staff/', RegistroStaffViewSet.as_view(), name='registro-staff'),
    url(r'^registro-producto-almacen/', RegistroAlmacenEnProductoViewSet.as_view(), name='registro-producto-almacen'),
    url(r'^registro-movimiento-producto/', RegistroMovimientoProductoViewSet.as_view(), name='registro-movimiento-producto'),
    url(r'^registro-producto/', RegistroProductoViewSet.as_view(), name='registro-producto'),
    url(r'^editar-staff/$', EditarStaffViewSet.as_view(), name='editar-staff'),
    url(r'^editar-producto/$', EditarProductoViewSet.as_view(), name='editar-producto'),
    url(r'^editar-staff/(?P<pk>\d+)/$', EditarStaffViewSet.as_view(), name='editar-staff'),
    url(r'^editar-producto/(?P<pk>\d+)/$', EditarProductoViewSet.as_view(), name='editar-producto'),
    url(r'^listado-staff/', ListadoStaffViewSet.as_view(), name='listado-staff'),
    url(r'^listado-producto/', ListadoProductoViewSet.as_view(), name='listado-producto'),
    url(r'^listado-almacen-producto/', ListadoAlmacenProductoViewSet.as_view(), name='listado-almacen-producto'),
    url(r'^listado-movimiento-producto/', ListadoMovimientoProductoViewSet.as_view(), name='listado-movimiento-producto'),
    url(r'^erro-pagina/', ErrorPaginaViewSet.as_view(), name='erro-pagina'),
]

app_dashboard/models/almacen.py
from django.db import models

from app_dashboard.models.producto import Producto
from app_dashboard.utilitarios.genericos import CleanCharField


class Almacen(models.Model):
    nombre = CleanCharField(blank=False, null=False, max_length=100)
    descripcion = CleanCharField(blank=False, null=False, max_length=200)
    direccion = CleanCharField(blank=False, null=False, max_length=200)
    almacen_producto = models.ManyToManyField(Producto, through='AlamacenProducto')

    def __str__(self):
        return self.nombre


class AlamacenProducto(models.Model):
    almacen = models.ForeignKey(Almacen, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    stock_minimo = models.IntegerField()
    stock_maximo = models.IntegerField()
    stock_actual = models.IntegerField()

    def __str__(self):
        return self.almacen.nombre + ' - ' + self.producto.nombre

app_dashboard/models/categoria.py
from django.db import models

from app_dashboard.utilitarios.genericos import CleanCharField


class Categoria(models.Model):
    nombre = CleanCharField(blank=False, null=False, max_length=100)
    descripcion = CleanCharField(blank=False, null=False, max_length=200)

    def __str__(self):
        return self.nombre

app_dashboard/models/cliente.py
from app_dashboard.models.usuario_abstract import UsuarioAbstract


class Cliente(UsuarioAbstract):
    pass

app_dashboard/models/movimiento.py
from django.db import models
from datetime import datetime

from app_dashboard.models.producto import Producto
from app_dashboard.models.usuario import Usuario

TIPO_MOVIMIENTO = (
    ('entrada', 'entrada'),
    ('salida', 'salida')
)


class Movimiento(models.Model):
    fecha_movimiento = models.DateTimeField(null=False, blank=False)
    tipo_movimiento = models.CharField(null=False, blank=False, choices=TIPO_MOVIMIENTO, max_length=50)
    usuario = models.ForeignKey(Usuario, on_delete=False)
    movimiento_producto = models.ManyToManyField(Producto, through="MovimientoProducto")

    def __str__(self):
        return self.tipo_movimiento + ' - ' + self.usuario.first_name


class MovimientoProducto(models.Model):
    movimiento = models.ForeignKey(Movimiento, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField(null=False, blank=False)

app_dashboard/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.core.exceptions import ValidationError


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={"type": "email", "name": "username", "id": "username", "class": "form-control form-control-user"}),
        required=True)
    password = forms.CharField(widget=forms.TextInput(
        attrs={"type": "password", "name": "password", "id": "password", "class": "form-control form-control-user"}),
        required=True)

    def confirm_login_allowed(self, user):
        if not (user.is_staff and user.is_active and not user.is_block):
            raise forms.ValidationError(
                self.error_messages['inactive'],
                code='inactive',
            )

    def clean(self):
        clean_data = self.cleaned_data
        self.user_cache = authenticate(**{'username': clean_data['username'], 'password': clean_data['password']})
        if self.user_cache is None:
            raise ValidationError("Datos incorrectos.")
        else:
            self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

app_dashboard/api/views.py
import os

import qrcode
from django.db import transaction
from rest_framework import mixins, status
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from ProjectIntegrador.settings import MEDIA_ROOT
from app_dashboard.api.permissions import AdminPermission, StaffGeneralPermission
from app_dashboard.api.serializers import *
from app_dashboard.models.almacen import Almacen
from app_dashboard.models.movimiento import MovimientoProducto, Movimiento
from app_dashboard.models.producto import Producto
from app_dashboard.models.staff import Staff


class CrearStaffViewSet(mixins.CreateModelMixin, GenericViewSet):
    permission_classes = (AdminPermission,)
    serializer_class = StaffSerializer
    queryset = Staff.objects.all()


class CrearProductoViewSet(mixins.CreateModelMixin, GenericViewSet):
    permission_classes = (AdminPermission, StaffGeneralPermission,)
    serializer_class = PorductoSerializer
    queryset = Producto.objects.all()

    def create(self, request, *args, **kwargs):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=1,
        )
        data_categoria = Categoria.objects.get(id=int(request.POST['categoria']))
        data_tipo_unidad = TipoUnidad.objects.get(id=int(request.POST['tipo_unidad']))
        data = {
            'nombre': request.POST['nombre'],
            'descripcion': request.POST['descripcion'],
            'categoria': {
                'nombre': data_categoria.nombre,
                'descripcion': data_categoria.descripcion
            },
            'tipo_unidad': {
                'nombre': data_tipo_unidad.nombre,
                'descripcion': data_tipo_unidad.descripcion,
                'conversion': {
                    'nombre': data_tipo_unidad.conversion.nombre,
                    'descripcion': data_tipo_unidad.conversion.descripcion
                }
            },
            'precio': request.POST['precio']
        }
        qr.add_data(data)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        ruta_save = os.path.join(MEDIA_ROOT, 'qr_product_' + request.POST['nombre']) + '.png'
        img.save(ruta_save)
        post = request.POST.copy()
        post['codigo_qr'] = ruta_save
        serializer = self.get_serializer(data=post)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)


class CrearAlmacenProductoViewSet(mixins.CreateModelMixin, GenericViewSet):
    permission_classes = (AdminPermission, StaffGeneralPermission,)
    serializer_class = AlmacenProductoSerializer
    queryset = AlamacenProducto.objects.all()

    @transaction.atomic()
    def create(self, request, *args, **kwargs):
        for data in request.data:
            data_almacen = Almacen.objects.get(id=int(data['almacen']))
            data_producto = Producto.objects.get(id=int(data['producto']))
            almacen = AlamacenProducto(stock_actual=data['stock_actual'], stock_maximo=data['stock_maximo'],
                                       stock_minimo=data['stock_minimo'], almacen=data_almacen, producto=data_producto)
            almacen.save()
        return Response(request.data, status=status.HTTP_200_OK, template_name=None, content_type=None)


class CrearQRViewSet(mixins.CreateModelMixin, GenericViewSet):
    permission_classes = (AdminPermission, StaffGeneralPermission,)
    serializer_class = PorductoSerializer
    queryset = Producto.objects.all()

    @transaction.atomic()
    def create(self, request, *args, **kwargs):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=1,
        )
        producto = Producto.objects.get(id=request.data['id'])
        data = {
            'nombre': producto.nombre,
            'descripcion': producto.descripcion,
            'categoria': {
                'nombre': producto.categoria.nombre,
                'descripcion': producto.categoria.descripcion
            },
            'tipo_unidad': {
                'nombre': producto.tipo_unidad.nombre,
                'descripcion': producto.tipo_unidad.descripcion,
                'conversion': {
                    'nombre': producto.tipo_unidad.conversion.nombre,
                    'descripcion': producto.tipo_unidad.conversion.descripcion
                }
            },
            'precio': producto.precio
        }
        qr.add_data(data)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        ruta_save = os.path.join('media', 'qr_product_' + producto.nombre) + '.png'
        img.save(ruta_save)
        producto.codigo_qr = ruta_save
        producto.save()
        return Response(request.data, status=status.HTTP_200_OK, template_name=None, content_type=None)


class CrearMovimientoProductoViewSet(mixins.CreateModelMixin, GenericViewSet):
    permission_classes = (AdminPermission, StaffGeneralPermission,)
    serializer_class = MovimientoProductoSerializer
    queryset = MovimientoProducto.objects.all()

    @transaction.atomic()
    def create(self, request, *args, **kwargs):
        for data in request.data:
            movimiento = Movimiento(fecha_movimiento=data['fecha_movimiento'], usuario=request.user,
                                    tipo_movimiento=data['tipo_movimiento_id'])
            movimiento.save()
            data_producto = Producto.objects.get(id=int(data['producto_id']))
            mov_prod = MovimientoProducto(movimiento=movimiento, producto=data_producto, cantidad=int(data['cantidad']))
            mov_prod.save()
        return Response(request.data, status=status.HTTP_200_OK, template_name=None, content_type=None)


class ListarStaffViewSet(mixins.ListModelMixin, GenericViewSet):
    permission_classes = (StaffGeneralPermission,)
    serializer_class = StaffListSerializer
    queryset = Staff.objects.all()


class ListarProductoViewSet(mixins.ListModelMixin, GenericViewSet):
    permission_classes = (AdminPermission, StaffGeneralPermission,)
    serializer_class = PorductoListSerializer
    queryset = Producto.objects.all()


class ListarAlmacenProductoViewSet(mixins.ListModelMixin, GenericViewSet):
    permission_classes = (AdminPermission, StaffGeneralPermission,)
    serializer_class = AlmacenProductoListarSerializer
    queryset = AlamacenProducto.objects.all()


class ListarMovimientoProductoViewSet(mixins.ListModelMixin, GenericViewSet):
    permission_classes = (AdminPermission, StaffGeneralPermission,)
    serializer_class = ListMovimientoProductoSerializer
    queryset = MovimientoProducto.objects.all()


class EditarStaffViewSet(mixins.UpdateModelMixin, GenericViewSet):
    permission_classes = (AdminPermission, StaffGeneralPermission,)
    serializer_class = StaffSerializer
    queryset = Staff.objects.all()


class EliminarProductoViewSet(mixins.DestroyModelMixin, GenericViewSet):
    permission_classes = (AdminPermission, StaffGeneralPermission,)
    serializer_class = PorductoSerializer
    queryset = Producto.objects.all()


class EliminarStaffViewSet(mixins.DestroyModelMixin, GenericViewSet):
    permission_classes = (AdminPermission,)
    serializer_class = StaffListSerializer
    queryset = Staff.objects.all()


class EditarProductoViewSet(mixins.UpdateModelMixin, GenericViewSet):
    permission_classes = (AdminPermission, StaffGeneralPermission,)
    serializer_class = PorductoSerializer
    queryset = Producto.objects.all()

    def update(self, request, *args, **kwargs):
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=1,
        )
        data_categoria = Categoria.objects.get(id=int(request.POST['categoria']))
        data_tipo_unidad = TipoUnidad.objects.get(id=int(request.POST['tipo_unidad']))
        data = {
            'nombre': request.POST['nombre'],
            'descripcion': request.POST['descripcion'],
            'categoria': {
                'nombre': data_categoria.nombre,
                'descripcion': data_categoria.descripcion
            },
            'tipo_unidad': {
                'nombre': data_tipo_unidad.nombre,
                'descripcion': data_tipo_unidad.descripcion,
                'conversion': {
                    'nombre': data_tipo_unidad.conversion.nombre,
                    'descripcion': data_tipo_unidad.conversion.descripcion
                }
            },
            'precio': request.POST['precio']
        }
        qr.add_data(data)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        ruta_save = os.path.join(MEDIA_ROOT, 'qr_product_' + request.POST['nombre']) + '.png'
        img.save(ruta_save)
        post = request.POST.copy()
        # post['codigo_qr'] = ruta_save
        instance = self.get_object()
        instance.nombre = post['nombre']
        instance.descripcion = post['descripcion']
        instance.categoria = data_categoria
        instance.tipo_unidad = data_tipo_unidad
        instance.precio = post['precio']
        instance.codigo_qr = ruta_save
        instance.save()

        serializer = self.get_serializer(instance)

        return Response(serializer.data)


class EliminarAlmacenProductoViewSet(mixins.DestroyModelMixin, GenericViewSet):
    permission_classes = (AdminPermission, StaffGeneralPermission,)
    serializer_class = AlmacenProductoSerializer
    queryset = AlamacenProducto.objects.all()


class EliminarMovimientoProductoViewSet(mixins.DestroyModelMixin, GenericViewSet):
    permission_classes = (AdminPermission, StaffGeneralPermission,)

app_dashboard/templates/editar_producto.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js %}
    <script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
    <script src="{% static 'template/js/editar_producto.js' %}"></script>
{% endblock %}

{% block container %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Registro de producto</h1>
    </div>

    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-12 col-md-12 mb-12">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <form id="form" class="user col-sm-12 mb-12 mb-sm-12"
                              data-url-edit="{% url 'app_dashboard:api:editar-producto-detail' producto.id %}"
                              data-url-refresh="{% url 'app_dashboard:editar-producto' producto.id %}">
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <label for="nombre"></label>
                                    <input type="text" class="form-control form-control-user" id="nombre" name="nombre"
                                           placeholder="Nombre de producto" value="{{ producto.nombre }}">
                                </div>
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <label for="descripcion"></label>
                                    <input type="text" class="form-control form-control-user" id="descripcion"
                                           name="descripcion" placeholder="Descripcion"
                                           value="{{ producto.descripcion }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-4 mb-3 mb-sm-0">
                                    <label for="categoria"></label>
                                    <select id="categoria" name="categoria" class="form-control">
                                        <option value="">-- Seleccione categoria --</option>
                                        {% for categoria in ls_categoria %}
                                            <option value="{{ categoria.id }}"
                                                    {% if categoria.id == producto.categoria.id %}
                                                    selected {% endif %}>{{ categoria.nombre }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-sm-4 mb-3 mb-sm-0">
                                    <label for="tipo_unidad"></label>
                                    <select id="tipo_unidad" name="tipo_unidad" class="form-control">
                                        <option value="">-- Seleccione tipo de unidad --</option>
                                        {% for tipo_unidad in ls_tipo_unidad %}
                                            <option value="{{ tipo_unidad.id }}"
                                                    {% if tipo_unidad.id == producto.tipo_unidad.id %}
                                                    selected {% endif %}>{{ tipo_unidad.nombre }}
                                                / {{ tipo_unidad.conversion.nombre }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-sm-4 mb-3 mb-sm-0">
                                    <label for="precio"></label>
                                    <input type="text" class="form-control form-control-user" id="precio" name="precio"
                                           placeholder="Precio" value="{{ producto.precio }}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-12 mb-6 mb-sm-0">
                                    <button type="submit" class="btn btn-facebook btn-block">Guardar</button>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="col-xl-4 col-lg-5" style="margin: 0 auto">
                        <div class="card shadow mb-4">
                            <!-- Card Header - Dropdown -->
                            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                                <h6 class="m-0 font-weight-bold text-primary">Codigo QR</h6>
                            </div>
                            <!-- Card Body -->
                            <div class="card-body">
                                <a href="#" type="text/css" id="imprimir" data-id="{{ path_img }}">Imprimir</a>
                                <div class="">
                                    <img src="{{ path_img }}" style="width: 100%; height: 100%">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

app_dashboard/templates/error_404.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js %}
    <script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
    <script src="{% static 'template/js/registro_staff.js' %}"></script>
{% endblock %}

{% block container %}
    <div class="text-center">
        <div class="error mx-auto" data-text="404">404</div>
        <p class="lead text-gray-800 mb-5">Page Not Found</p>
        <p class="text-gray-500 mb-0">It looks like you found a glitch in the matrix...</p>
        <a href="{% url 'app_dashboard:listado-producto' %}">&larr; Back to Dashboard</a>
    </div>
{% endblock %}

app_dashboard/templates/listado_producto.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'template/js/listado_producto.js' %}"></script>
{% endblock %}

{% block container %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Listado de producto</h1>
    </div>

    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-12 col-md-12 mb-12">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="listado_producto"
                                   data-url-list="{% url 'app_dashboard:api:listar-producto-list' %}"
                                   data-producto-edit="{% url 'app_dashboard:editar-producto' %}"
                                   data-eliminar="{% url 'app_dashboard:api:eliminar-producto-detail' 0 %}"
                                   data-url-refresh="{% url 'app_dashboard:listado-producto' %}"
                                   data-crear-qr="{% url 'app_dashboard:api:crear-qr-list' %}">
                                <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Categoria</th>
                                    <th>Tipo unidad</th>
                                    <th>Acciones</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modalEliminar" tabindex="-1" role="dialog" aria-labelledby="modalEliminarLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalEliminarLabel">¿Desea eliminar el producto?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button type="button" class="btn btn-primary modal_eliminar" data-id="">Eliminar</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modalCrearQR" tabindex="-1" role="dialog" aria-labelledby="modalCrearQRLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalCrearQRLabel">¿Desea crear el codigo QR?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button type="button" class="btn btn-primary modal_QR" data-id="">Crear</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app_dashboard/templates/listado_staff.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block js %}
    <script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
    <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'template/js/listado_staff.js' %}"></script>
{% endblock %}

{% block container %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Listado de staff</h1>
    </div>

    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-12 col-md-12 mb-12">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="listado_staff"
                                   data-url-list="{% url 'app_dashboard:api:listar-staff-list' %}"
                                   data-staff-edit="{% url 'app_dashboard:editar-staff' %}"
                                   data-eliminar="{% url 'app_dashboard:api:eliminar-staff-detail' 0 %}"
                                   data-url-refresh="{% url 'app_dashboard:listado-staff' %}">
                                <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Apellido Paterno</th>
                                    <th>Apellido Materno</th>
                                    <th>Edad</th>
                                    <th>Correo</th>
                                    <th># Doc</th>
                                    <th>Telefono</th>
                                    <th>Acciones</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modalEliminar" tabindex="-1" role="dialog" aria-labelledby="modalEliminarLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalEliminarLabel">¿Desea eliminar el staff?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                    <button type="button" class="btn btn-primary modal_eliminar" data-id="">Eliminar</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}